
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Josué Zuniga
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmclase = new javax.swing.JPopupMenu();
        modificarc = new javax.swing.JMenuItem();
        eliminarc = new javax.swing.JMenuItem();
        pmmaestro = new javax.swing.JPopupMenu();
        modificarm = new javax.swing.JMenuItem();
        eliminarm = new javax.swing.JMenuItem();
        pmalumno = new javax.swing.JPopupMenu();
        enviar = new javax.swing.JMenuItem();
        modc = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        nc2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        sc1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        ed1 = new javax.swing.JSpinner();
        sl1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        aire1 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        modm = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        n3 = new javax.swing.JTextField();
        ap3 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        edad2 = new javax.swing.JSpinner();
        jLabel41 = new javax.swing.JLabel();
        g2 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        salario1 = new javax.swing.JTextField();
        clases1 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        modcrr = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        carr = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jf1 = new javax.swing.JTextField();
        costo1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        info = new javax.swing.JLabel();
        moda = new javax.swing.JDialog();
        tp = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        f1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jf = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nc1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ed = new javax.swing.JSpinner();
        sl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        aire = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ap1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        edad = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        g = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        c = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        ap2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        edad1 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        g1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        clases = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaclases = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listamaestros = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaalumnos = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        modificarc.setText("Modificar Clase");
        modificarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarcActionPerformed(evt);
            }
        });
        pmclase.add(modificarc);

        eliminarc.setText("Eliminar Clase");
        eliminarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcActionPerformed(evt);
            }
        });
        pmclase.add(eliminarc);

        modificarm.setText("Modificar Maestro");
        modificarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarmActionPerformed(evt);
            }
        });
        pmmaestro.add(modificarm);

        eliminarm.setText("Eliminar Maestro");
        eliminarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarmActionPerformed(evt);
            }
        });
        pmmaestro.add(eliminarm);

        enviar.setText("Enviar Alumno al Árbol");
        pmalumno.add(enviar);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 0, 204));
        jLabel31.setText("Ingrese el nombre de la clase");

        nc2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 0, 204));
        jLabel32.setText("Modificar Clase");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 0, 204));
        jLabel33.setText("Ingrese la sección de la clase");

        sc1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 0, 204));
        jLabel34.setText("Ingrese el Edificio de la clase");

        ed1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ed1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));

        sl1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 0, 204));
        jLabel35.setText("Ingrese el salón de la clase");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 0, 204));
        jLabel36.setText("¿Tiene aire acondicionado?");

        aire1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        aire1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("Guardar Clase");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(488, 488, 488)
                                .addComponent(jLabel32))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jLabel31)
                                .addGap(92, 92, 92)
                                .addComponent(nc2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36))
                            .addGap(92, 92, 92)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sc1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ed1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aire1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jButton8)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel32)
                .addGap(69, 69, 69)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nc2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(70, 70, 70)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sc1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(76, 76, 76)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ed1))
                .addGap(64, 64, 64)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(aire1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout modcLayout = new javax.swing.GroupLayout(modc.getContentPane());
        modc.getContentPane().setLayout(modcLayout);
        modcLayout.setHorizontalGroup(
            modcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1239, Short.MAX_VALUE)
            .addGroup(modcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modcLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        modcLayout.setVerticalGroup(
            modcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(modcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modcLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 0, 204));
        jLabel37.setText("Modificar Maestro");

        n3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        ap3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 0, 204));
        jLabel38.setText("Apellido:");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 0, 204));
        jLabel39.setText("Nombre:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 0, 204));
        jLabel40.setText("Edad:");

        edad2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        edad2.setModel(new javax.swing.SpinnerNumberModel(30, 30, 70, 1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 0, 204));
        jLabel41.setText("Género:");

        g2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        g2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("Guardar Maestro");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 0, 204));
        jLabel42.setText("Salario:");

        salario1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        clases1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 0, 204));
        jLabel43.setText("Clases:");

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("Agregar Clase Seleccionada");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(227, 227, 227)
                            .addComponent(jLabel37))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(jLabel39)
                            .addGap(70, 70, 70)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edad2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ap3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(jButton9)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(70, 70, 70)
                                .addComponent(salario1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(70, 70, 70)
                                .addComponent(clases1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(27, 27, 27)
                .addComponent(jButton10)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel37)
                .addGap(54, 54, 54)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(ap3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(edad2))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(salario1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clases1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10)))
                .addGap(115, 115, 115)
                .addComponent(jButton9)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout modmLayout = new javax.swing.GroupLayout(modm.getContentPane());
        modm.getContentPane().setLayout(modmLayout);
        modmLayout.setHorizontalGroup(
            modmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1239, Short.MAX_VALUE)
            .addGroup(modmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modmLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        modmLayout.setVerticalGroup(
            modmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(modmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modmLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 0, 204));
        jLabel44.setText("Modificar Carrera");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 0, 204));
        jLabel45.setText("Seleccione la facultad");

        carr.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        carr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                carrItemStateChanged(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 0, 204));
        jLabel46.setText("Carrera a modificar: ");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 0, 204));
        jLabel47.setText("Ingrese el Jefe de Carrera");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 0, 204));
        jLabel48.setText("Ingrese el costo de la Carrera");

        jf1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        costo1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setText("Guardar Carrera");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        info.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        info.setForeground(new java.awt.Color(51, 0, 204));
        info.setText("     ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jLabel44))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45)
                            .addComponent(jLabel48))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(carr, 0, 324, Short.MAX_VALUE)
                                .addComponent(jf1)
                                .addComponent(costo1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jButton11)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel44)
                .addGap(74, 74, 74)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(carr, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(info))
                .addGap(99, 99, 99)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jf1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47))
                .addGap(80, 80, 80)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout modcrrLayout = new javax.swing.GroupLayout(modcrr.getContentPane());
        modcrr.getContentPane().setLayout(modcrrLayout);
        modcrrLayout.setHorizontalGroup(
            modcrrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1239, Short.MAX_VALUE)
            .addGroup(modcrrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modcrrLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        modcrrLayout.setVerticalGroup(
            modcrrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(modcrrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(modcrrLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout modaLayout = new javax.swing.GroupLayout(moda.getContentPane());
        moda.getContentPane().setLayout(modaLayout);
        modaLayout.setHorizontalGroup(
            modaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        modaLayout.setVerticalGroup(
            modaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tp.setForeground(new java.awt.Color(51, 0, 204));
        tp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 204));
        jLabel1.setText("Bienvenido a UNITEC");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_UNITEC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(311, 311, 311))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        tp.addTab("Inicio", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Nueva Carrera");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setText("Seleccione la facultad");

        f1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        f1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciaturas", "Ingenierías", "Ciencias de la Salud" }));
        f1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                f1ItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 204));
        jLabel5.setText("Seleccione la carrera");

        c1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 204));
        jLabel6.setText("Ingrese el Jefe de Carrera");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 204));
        jLabel7.setText("Ingrese el costo de la Carrera");

        jf.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        costo.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Guardar Carrera");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(f1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c1, 0, 324, Short.MAX_VALUE)
                            .addComponent(jf)
                            .addComponent(costo, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jButton1)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        tp.addTab("Agregar Carreras", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 204));
        jLabel8.setText("Ingrese el nombre de la clase");

        nc1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 204));
        jLabel9.setText("Nueva Clase");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 204));
        jLabel10.setText("Ingrese la sección de la clase");

        sc.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 204));
        jLabel11.setText("Ingrese el Edificio de la clase");

        ed.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ed.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));

        sl.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 204));
        jLabel12.setText("Ingrese el salón de la clase");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 204));
        jLabel13.setText("¿Tiene aire acondicionado?");

        aire.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        aire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Guardar Clase");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(488, 488, 488)
                                .addComponent(jLabel9))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jLabel8)
                                .addGap(92, 92, 92)
                                .addComponent(nc1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(92, 92, 92)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(aire, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jButton2)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel9)
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nc1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ed))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(aire, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
        );

        tp.addTab("Agregar Clases", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 204));
        jLabel14.setText("Nuevo Estudiante");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 204));
        jLabel15.setText("Nombre:");

        n1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 204));
        jLabel16.setText("Apellido:");

        ap1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 204));
        jLabel17.setText("Edad:");

        edad.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        edad.setModel(new javax.swing.SpinnerNumberModel(16, 16, 60, 1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 204));
        jLabel18.setText("Género:");

        g.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        g.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 204));
        jLabel19.setText("#Cuenta:");

        cn.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 204));
        jLabel20.setText("Carrera:");

        c.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Guardar Estudiante");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Validar Numero de Cuenta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(70, 70, 70)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(70, 70, 70)
                                .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(70, 70, 70)
                                .addComponent(c, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addComponent(jButton6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jButton3)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel14)
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(edad))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115)
                .addComponent(jButton3)
                .addGap(60, 60, 60))
        );

        tp.addTab("Agregar Estudiante", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 204));
        jLabel21.setText("Nuevo Maestro");

        n2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        ap2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 204));
        jLabel22.setText("Apellido:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 204));
        jLabel23.setText("Nombre:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 204));
        jLabel24.setText("Edad:");

        edad1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        edad1.setModel(new javax.swing.SpinnerNumberModel(30, 30, 70, 1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 204));
        jLabel25.setText("Género:");

        g1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        g1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Guardar Maestro");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 204));
        jLabel26.setText("Salario:");

        salario.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        clases.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 204));
        jLabel27.setText("Clases:");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Agregar Clase Seleccionada");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(227, 227, 227)
                            .addComponent(jLabel21))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(70, 70, 70)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(edad1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(jButton4)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(70, 70, 70)
                                .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(70, 70, 70)
                                .addComponent(clases, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)))
                .addGap(27, 27, 27)
                .addComponent(jButton5)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel21)
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(edad1))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addGap(115, 115, 115)
                .addComponent(jButton4)
                .addGap(31, 31, 31))
        );

        tp.addTab("Agregar Maestro", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 204));
        jLabel28.setText("Clases");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 204));
        jLabel29.setText("Maestros");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 204));
        jLabel30.setText("Estudiantes");

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        listaclases.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        listaclases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaclasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaclases);

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        listamaestros.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        listamaestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listamaestrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listamaestros);

        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        listaalumnos.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        listaalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaalumnosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaalumnos);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Ir a Modificar Carreras");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(279, 279, 279)
                .addComponent(jLabel30)
                .addGap(128, 128, 128))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel28))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        tp.addTab("Listas", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1239, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );

        tp.addTab("Árbol", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_f1ItemStateChanged
        refresh();
    }//GEN-LAST:event_f1ItemStateChanged

    private void tpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpStateChanged
        if (tp.getSelectedIndex() == 1) {
            refresh();
        }
        if (tp.getSelectedIndex() == 3) {
            if (carreras.isEmpty()) {
                n1.setEnabled(false);
                ap1.setEnabled(false);
                edad.setEnabled(false);
                g.setEnabled(false);
                cn.setEnabled(false);
                c.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Primero debe agregar una carrera");
            } else {
                n1.setEnabled(true);
                ap1.setEnabled(true);
                edad.setEnabled(true);
                g.setEnabled(true);
                cn.setEnabled(true);
                c.setEnabled(true);
                DefaultComboBoxModel m = (DefaultComboBoxModel) c.getModel();
                for (int i = 0; i < carreras.size(); i++) {
                    m.addElement(carreras.get(i).getNombre());
                }
                c.setModel(m);
            }
        }
        if (tp.getSelectedIndex() == 4) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) clases.getModel();
            for (int i = 0; i < cl.size(); i++) {
                m.addElement(cl.get(i));
            }
            clases.setModel(m);
        }
        if (tp.getSelectedIndex() == 5) {
            DefaultListModel modelo
                    = (DefaultListModel) listaclases.getModel();
            for (int i = 0; i < cl.size(); i++) {
                modelo.addElement(cl.get(i));
            }
            listaclases.setModel(modelo);
            DefaultListModel modelo1
                    = (DefaultListModel) listamaestros.getModel();
            for (int i = 0; i < p.size(); i++) {
                if (p.get(i) instanceof Maestro) {
                    modelo1.addElement(cl.get(i));
                }
            }
            listamaestros.setModel(modelo1);
            DefaultListModel modelo2
                    = (DefaultListModel) listaalumnos.getModel();
            for (int i = 0; i < p.size(); i++) {
                if (p.get(i) instanceof Estudiante) {
                    modelo2.addElement(cl.get(i));
                }
            }
            listaalumnos.setModel(modelo2);
        }
    }//GEN-LAST:event_tpStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String facultad = f1.getSelectedItem().toString();
        String tipo = "";
        String jefe = jf.getText();
        double cst = Double.parseDouble(costo.getText());
        if (facultad.equals("Licenciaturas")) {
            tipo = c1.getSelectedItem().toString();
            if (carrera(tipo)) {
                JOptionPane.showMessageDialog(null, "No pueden haber dos carreras del mismo tipo\n"
                        + "La carrera no fue agregada");
            } else {
                Licenciaturas x = new Licenciaturas(tipo, facultad, cst, jefe);
                carreras.add(x);
                JOptionPane.showMessageDialog(null, "Carrera agregada correctamente");
                jf.setText("");
                costo.setText("");
            }
        }
        if (facultad.equals("Ingenierías")) {
            tipo = c1.getSelectedItem().toString();
            if (carrera(tipo)) {
                JOptionPane.showMessageDialog(null, "No pueden haber dos carreras del mismo tipo\n"
                        + "La carrera no fue agregada");
            } else {
                Ingenierias x = new Ingenierias(tipo, facultad, cst, jefe);
                carreras.add(x);
                JOptionPane.showMessageDialog(null, "Carrera agregada correctamente");
                jf.setText("");
                costo.setText("");
            }
        }
        if (facultad.equals("Ciencias de la Salud")) {
            tipo = c1.getSelectedItem().toString();
            if (carrera(tipo)) {
                JOptionPane.showMessageDialog(null, "No pueden haber dos carreras del mismo tipo\n"
                        + "La carrera no fue agregada");
            } else {
                Salud x = new Salud(tipo, facultad, cst, jefe);
                carreras.add(x);
                JOptionPane.showMessageDialog(null, "Carrera agregada correctamente");
                jf.setText("");
                costo.setText("");
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre = nc1.getText();
        int s = Integer.parseInt(sc.getText());
        int e = ((Integer) ed.getValue());
        int salon = Integer.parseInt(sl.getText());
        boolean a = false;
        String aux = aire.getSelectedItem().toString();
        if (aux.equals("Si")) {
            a = true;
        } else {
            a = false;
        }
        Clases x = new Clases(nombre, s, e, salon, a);
        cl.add(x);
        JOptionPane.showMessageDialog(null, "Clase agregada correctamente");
        nc1.setText("");
        ed.setValue(1);
        sl.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nombre = n1.getText();
        String apellido = ap1.getText();
        int age = ((Integer) edad.getValue());
        String genero = g.getSelectedItem().toString();
        int cuenta = Integer.parseInt(cn.getText());
        Carrera cr = ((Carrera) c.getSelectedItem());
        Estudiante e = new Estudiante(cuenta, cr, nombre, apellido, age, genero);
        p.add(e);
        JOptionPane.showMessageDialog(null, "Estudiante agregado correctamente");
        n1.setText("");
        ap1.setText("");
        edad.setValue(16);
        cn.setText("");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        int cuenta = Integer.parseInt(cn.getText());
        if (numc.contains(cuenta)) {
            flag = true;
            jButton3.setEnabled(true);
        } else {
            flag = false;
            jButton3.setEnabled(true);
        }
        while (flag) {
            JOptionPane.showMessageDialog(null, "El numero de cuenta ya existe\n"
                    + "Por favor ingrese uno nuevo");
            cn.setText("");
            if (numc.contains(cuenta)) {
                flag = true;
                jButton3.setEnabled(false);
            } else {
                flag = false;
                jButton3.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String nombre = n2.getText();
        String apellido = ap2.getText();
        int age = ((Integer) edad1.getValue());
        String genero = g1.getSelectedItem().toString();
        double s = Double.parseDouble(salario.getText());
        Maestro m = new Maestro(s, nombre, apellido, age, genero);
        m.setClases(aux);
        p.add(m);
        aux = new ArrayList();
        JOptionPane.showMessageDialog(null, "Maestro agregado correctamente");
        n2.setText("");
        ap2.setText("");
        edad1.setValue(30);
        salario.getText();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Clases x = ((Clases) clases.getSelectedItem());
        aux.add(x);
        JOptionPane.showMessageDialog(null, "Clase agregada correctamente");
    }//GEN-LAST:event_jButton5MouseClicked

    private void eliminarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcActionPerformed
        DefaultListModel modelo
                = (DefaultListModel) listaclases.getModel();
        Clases x = ((Clases) modelo.get(listaclases.getSelectedIndex()));
        if (cl.contains(x)) {
            cl.remove(x);
            modelo.remove(listaclases.getSelectedIndex());
            listaclases.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Clase eliminada correctamente");
        }
    }//GEN-LAST:event_eliminarcActionPerformed

    private void listaclasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaclasesMouseClicked
        if (listaclases.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pmclase.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_listaclasesMouseClicked

    private void listamaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listamaestrosMouseClicked
        if (listamaestros.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pmmaestro.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_listamaestrosMouseClicked

    private void listaalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaalumnosMouseClicked
        if (listaalumnos.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pmalumno.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_listaalumnosMouseClicked

    private void eliminarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarmActionPerformed
        DefaultListModel modelo
                = (DefaultListModel) listamaestros.getModel();
        Maestro m = ((Maestro) modelo.get(listamaestros.getSelectedIndex()));
        if (p.contains(m)) {
            p.remove(m);
            modelo.remove(listamaestros.getSelectedIndex());
            listamaestros.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Maestro eliminado correctamente");
        }
    }//GEN-LAST:event_eliminarmActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        DefaultListModel modelo
                = (DefaultListModel) listaclases.getModel();
        Clases x = ((Clases) modelo.get(listaclases.getSelectedIndex()));
        if (cl.contains(x)) {
            String nombre = nc2.getText();
            int s = Integer.parseInt(sc1.getText());
            int e = ((Integer) ed1.getValue());
            int salon = Integer.parseInt(sl1.getText());
            boolean a = false;
            String aux = aire1.getSelectedItem().toString();
            if (aux.equals("Si")) {
                a = true;
            } else {
                a = false;
            }
            for (int i = 0; i < cl.size(); i++) {
                if (cl.get(i).equals(x)) {
                    cl.get(i).setNombre(nombre);
                    cl.get(i).setEdificio(e);
                    cl.get(i).setSeccion(s);
                    cl.get(i).setSalon(salon);
                    cl.get(i).setAire(a);
                }
            }
            DefaultComboBoxModel m = (DefaultComboBoxModel) clases.getModel();
            for (int i = 0; i < cl.size(); i++) {
                m.addElement(cl.get(i).getNombre());
            }
            clases.setModel(m);
            DefaultListModel modelo1
                    = (DefaultListModel) listaclases.getModel();
            for (int i = 0; i < cl.size(); i++) {
                modelo1.addElement(cl.get(i));
            }
            listaclases.setModel(modelo1);
            JOptionPane.showMessageDialog(null, "Clase modificada correctamente");
            nc1.setText("");
            ed.setValue(1);
            sl.setText("");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void modificarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarcActionPerformed
        modc.setModal(true);
        modc.pack();
        modc.setLocationRelativeTo(this);
        modc.setVisible(true);
    }//GEN-LAST:event_modificarcActionPerformed

    private void modificarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarmActionPerformed
        modm.setModal(true);
        modm.pack();
        modm.setLocationRelativeTo(this);
        modm.setVisible(true);
    }//GEN-LAST:event_modificarmActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        DefaultListModel modelo
                = (DefaultListModel) listamaestros.getModel();
        Maestro m = ((Maestro) modelo.get(listamaestros.getSelectedIndex()));
        if (p.contains(m)) {
            String nombre = n3.getText();
            String apellido = ap3.getText();
            int age = ((Integer) edad2.getValue());
            String genero = g2.getSelectedItem().toString();
            double s = Double.parseDouble(salario1.getText());
            for (int i = 0; i < p.size(); i++) {
                if (p.get(i).equals(m) && p.get(i) instanceof Maestro) {
                    p.get(i).setNombre(nombre);
                    p.get(i).setApellido(apellido);
                    p.get(i).setEdad(age);
                    p.get(i).setGenero(genero);
                    ((Maestro) p.get(i)).setSalario(s);
                    ((Maestro) p.get(i)).setClases(aux);
                }
            }
            DefaultListModel modelo1
                    = (DefaultListModel) listamaestros.getModel();
            for (int i = 0; i < p.size(); i++) {
                if (p.get(i) instanceof Maestro) {
                    modelo1.addElement(cl.get(i));
                }
            }
            listamaestros.setModel(modelo1);
            JOptionPane.showMessageDialog(null, "Maestro modificado correctamente");
            n3.setText("");
            aux = new ArrayList();
            ap3.setText("");
            edad2.setValue(30);
            salario1.getText();
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        Clases x = ((Clases) clases1.getSelectedItem());
        aux.add(x);
        JOptionPane.showMessageDialog(null, "Clase agregada correctamente");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        modcrr.setModal(true);
        modcrr.pack();
        modcrr.setLocationRelativeTo(this);
        modcrr.setVisible(true);
        DefaultComboBoxModel m = (DefaultComboBoxModel) carr.getModel();
        for (int i = 0; i < carreras.size(); i++) {
            m.addElement(carreras.get(i));
        }
        carr.setModel(m);
    }//GEN-LAST:event_jButton7MouseClicked

    private void carrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_carrItemStateChanged
        Carrera cr = ((Carrera)carr.getSelectedItem());
        info.setText(cr.getNombre());
    }//GEN-LAST:event_carrItemStateChanged

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        Carrera cr = ((Carrera)carr.getSelectedItem());
        String jefe = jf1.getText();
        double cst = Double.parseDouble(costo1.getText());
        for (int i = 0; i < carreras.size(); i++) {
            if (carreras.get(i).equals(cr)) {
                carreras.get(i).setJefe(jefe);
                carreras.get(i).setCosto(cst);
            }
        }
        DefaultComboBoxModel m = (DefaultComboBoxModel) carr.getModel();
        for (int i = 0; i < carreras.size(); i++) {
            m.addElement(carreras.get(i));
        }
        carr.setModel(m);
        c.setModel(m);
        jf1.setText("");
        costo1.setText("");
        JOptionPane.showMessageDialog(null, "Carrera modificada correctamente");
    }//GEN-LAST:event_jButton11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aire;
    private javax.swing.JComboBox<String> aire1;
    private javax.swing.JTextField ap1;
    private javax.swing.JTextField ap2;
    private javax.swing.JTextField ap3;
    private javax.swing.JComboBox<String> c;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> carr;
    private javax.swing.JComboBox<String> clases;
    private javax.swing.JComboBox<String> clases1;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField costo;
    private javax.swing.JTextField costo1;
    private javax.swing.JSpinner ed;
    private javax.swing.JSpinner ed1;
    private javax.swing.JSpinner edad;
    private javax.swing.JSpinner edad1;
    private javax.swing.JSpinner edad2;
    private javax.swing.JMenuItem eliminarc;
    private javax.swing.JMenuItem eliminarm;
    private javax.swing.JMenuItem enviar;
    private javax.swing.JComboBox<String> f1;
    private javax.swing.JComboBox<String> g;
    private javax.swing.JComboBox<String> g1;
    private javax.swing.JComboBox<String> g2;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jf;
    private javax.swing.JTextField jf1;
    private javax.swing.JList<String> listaalumnos;
    private javax.swing.JList<String> listaclases;
    private javax.swing.JList<String> listamaestros;
    private javax.swing.JDialog moda;
    private javax.swing.JDialog modc;
    private javax.swing.JDialog modcrr;
    private javax.swing.JMenuItem modificarc;
    private javax.swing.JMenuItem modificarm;
    private javax.swing.JDialog modm;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField nc1;
    private javax.swing.JTextField nc2;
    private javax.swing.JPopupMenu pmalumno;
    private javax.swing.JPopupMenu pmclase;
    private javax.swing.JPopupMenu pmmaestro;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField salario1;
    private javax.swing.JTextField sc;
    private javax.swing.JTextField sc1;
    private javax.swing.JTextField sl;
    private javax.swing.JTextField sl1;
    private javax.swing.JTabbedPane tp;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Carrera> carreras = new ArrayList();
    private ArrayList<Clases> cl = new ArrayList();
    private ArrayList<Persona> p = new ArrayList();
    private ArrayList<Integer> numc = new ArrayList();
    private boolean flag = false;
    private ArrayList<Clases> aux = new ArrayList();

    public void refresh() {
        if (f1.getSelectedItem().equals("Licenciaturas")) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) c1.getModel();
            m.addElement("Finanzas");
            m.addElement("Derecho");
            m.addElement("Administración de Empresas");
            m.addElement("Diseño Gráfico");
            m.addElement("Mercadotecnia");
            c1.setModel(m);
        }
        if (f1.getSelectedItem().equals("Ingenierías")) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) c1.getModel();
            m.addElement("Sistemas Computacionales");
            m.addElement("Industrial y de Sistemas");
            m.addElement("Mecatrónica");
            m.addElement("Biomédica");
            m.addElement("Energía");
            c1.setModel(m);
        }
        if (f1.getSelectedItem().equals("Ciencias de la Salud")) {
            DefaultComboBoxModel m = (DefaultComboBoxModel) c1.getModel();
            m.addElement("Medicina y Cirugía");
            m.addElement("Odontología");
            m.addElement("Nutrición");
            m.addElement("Terapia Física y Ocupacional");
            c1.setModel(m);
        }
    }// fin metodo refresh

    public boolean carrera(String tipo) {
        boolean r = false;
        for (int i = 0; i < carreras.size(); i++) {
            if (carreras.get(i) instanceof Licenciaturas) {
                if (((Licenciaturas) carreras.get(i)).getTipo().equals(tipo)) {
                    r = true;
                } else {
                    r = false;
                }
            }
            if (carreras.get(i) instanceof Ingenierias) {
                if (((Ingenierias) carreras.get(i)).getTipo().equals(tipo)) {
                    r = true;
                } else {
                    r = false;
                }
            }
            if (carreras.get(i) instanceof Salud) {
                if (((Salud) carreras.get(i)).getTipo().equals(tipo)) {
                    r = true;
                } else {
                    r = false;
                }
            }
        }
        return r;
    }
}
